# Generated by Django 2.0.5 on 2018-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('is_married', 'Женат'), ('married', 'Замужем'), ('single', 'Холост'), ('no_married', 'Не замужем')], max_length=20, verbose_name='Сем. статус'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('men', 'Мужской'), ('women', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
    ]
