# Generated by Django 2.0.5 on 2018-05-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20180524_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
    ]
