# Generated by Django 2.0.5 on 2018-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('name_institute', models.CharField(max_length=200, verbose_name='Название уч.заведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('image', models.ImageField(blank=True, upload_to='certificates', verbose_name='Изображение сертификата')),
                ('file', models.FileField(blank=True, upload_to='certificates', verbose_name='Файл сертификата')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institute', models.CharField(max_length=200, verbose_name='Название уч.заведения')),
                ('department', models.CharField(max_length=100, verbose_name='Факультет')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('date_begin', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('type', models.CharField(choices=[('secondary', 'Среднее'), ('higher', 'Высшее'), ('additional', 'Дополнительное')], max_length=30, verbose_name='Тип образования')),
                ('image', models.ImageField(blank=True, upload_to='education', verbose_name='Изображение диплома')),
            ],
        ),
    ]
