# Generated by Django 2.0.4 on 2018-05-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='podskills',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezumeapp.Skills'),
        ),
    ]
