# Generated by Django 2.0.4 on 2018-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0004_auto_20180520_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skills_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='podskills',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
