# Generated by Django 2.0.4 on 2018-05-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0005_auto_20180520_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodPodSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('podskills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezumeapp.PodSkills')),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
