# Generated by Django 2.0.4 on 2018-05-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0006_auto_20180520_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('img_preview', models.ImageField(upload_to='projects', verbose_name='Картинка (превью)')),
                ('img_1', models.ImageField(blank=True, upload_to='projects', verbose_name='Картинка 1')),
                ('img_2', models.ImageField(blank=True, upload_to='projects', verbose_name='Картинка 2')),
                ('img_3', models.ImageField(blank=True, upload_to='projects', verbose_name='Картинка 3')),
                ('img_4', models.ImageField(blank=True, upload_to='projects', verbose_name='Картинка 4')),
                ('file', models.FileField(blank=True, upload_to='projects', verbose_name='Файл проекта')),
                ('link', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на проект')),
                ('podskills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezumeapp.PodPodSkills')),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezumeapp.PodSkills')),
            ],
        ),
    ]
