# Generated by Django 2.0.4 on 2018-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0007_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='podskills',
        ),
        migrations.AddField(
            model_name='projects',
            name='podskills',
            field=models.ManyToManyField(blank=True, null=True, to='rezumeapp.PodPodSkills'),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='skills',
        ),
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='rezumeapp.PodSkills'),
        ),
    ]
