# Generated by Django 2.0.4 on 2018-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0008_auto_20180520_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='podskills',
            field=models.ManyToManyField(blank=True, to='rezumeapp.PodPodSkills'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(blank=True, to='rezumeapp.PodSkills'),
        ),
    ]
