# Generated by Django 2.0.5 on 2018-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezumeapp', '0010_auto_20180628_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='image_descr',
            field=models.CharField(blank=True, default='Сертификат', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='image_descr',
            field=models.CharField(blank=True, default='Диплом', max_length=100),
        ),
    ]
